name: CI for Server and Client

on:
  push:
    branches:
      - main

jobs:
  build-and-test-server:
    name: Build and Test Server
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main
        working-directory: ./server

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build project
        run: npm run build
        working-directory: ./server

  build-and-test-client:
    name: Build and Test Client
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main
        working-directory: ./client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build project
        run: npm run build
        working-directory: ./client
