name: Client CI

on:
  push:
    paths:
      - "client/**"
    branches: [ "main" ]
  
  pull_request:
    paths:
      - "client/**" 
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - run: npm install
      working-directory: ./client

    - run: npm run build --if-present
      working-directory: ./client
