# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on:
  push:
    paths:
      - "client/**"
    branches: [ "main" ]
  
  pull_request:
    paths:
      - "client/**" 
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set working directory
      id: set-working-directory
      run: echo "WORKDIR=$(pwd)/client" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: List files in client directory
      run: ls -la ${{ env.WORKDIR }}

    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.WORKDIR }}

    - name: Build the project
      run: npm run build --if-present
      working-directory: ${{ env.WORKDIR }}


