export const ArrayCountries = [
    { name: "Afghanistan", flags: "https://flagcdn.com/af.svg", callingCodes: "93" },
    { name: "Albania", flags: "https://flagcdn.com/al.svg", callingCodes: "355" },
    { name: "Algeria", flags: "https://flagcdn.com/dz.svg", callingCodes: "213" },
    { name: "Andorra", flags: "https://flagcdn.com/ad.svg", callingCodes: "376" },
    { name: "Angola", flags: "https://flagcdn.com/ao.svg", callingCodes: "244" },
    { name: "Antigua and Barbuda", flags: "https://flagcdn.com/ag.svg", callingCodes: "1268" },
    { name: "Argentina", flags: "https://flagcdn.com/ar.svg", callingCodes: "54" },
    { name: "Armenia", flags: "https://flagcdn.com/am.svg", callingCodes: "374" },
    { name: "Australia", flags: "https://flagcdn.com/au.svg", callingCodes: "61" },
    { name: "Austria", flags: "https://flagcdn.com/at.svg", callingCodes: "43" },
    { name: "Azerbaijan", flags: "https://flagcdn.com/az.svg", callingCodes: "994" },
    { name: "Bahamas", flags: "https://flagcdn.com/bs.svg", callingCodes: "1242" },
    { name: "Bahrain", flags: "https://flagcdn.com/bh.svg", callingCodes: "973" },
    { name: "Bangladesh", flags: "https://flagcdn.com/bd.svg", callingCodes: "880" },
    { name: "Barbados", flags: "https://flagcdn.com/bb.svg", callingCodes: "1246" },
    { name: "Belarus", flags: "https://flagcdn.com/by.svg", callingCodes: "375" },
    { name: "Belgium", flags: "https://flagcdn.com/be.svg", callingCodes: "32" },
    { name: "Belize", flags: "https://flagcdn.com/bz.svg", callingCodes: "501" },
    { name: "Benin", flags: "https://flagcdn.com/bj.svg", callingCodes: "229" },
    { name: "Bhutan", flags: "https://flagcdn.com/bt.svg", callingCodes: "975" },
    { name: "Bolivia", flags: "https://flagcdn.com/bo.svg", callingCodes: "591" },
    { name: "Bosnia and Herzegovina", flags: "https://flagcdn.com/ba.svg", callingCodes: "387" },
    { name: "Botswana", flags: "https://flagcdn.com/bw.svg", callingCodes: "267" },
    { name: "Brazil", flags: "https://flagcdn.com/br.svg", callingCodes: "55" },
    { name: "Brunei", flags: "https://flagcdn.com/bn.svg", callingCodes: "673" },
    { name: "Bulgaria", flags: "https://flagcdn.com/bg.svg", callingCodes: "359" },
    { name: "Burkina Faso", flags: "https://flagcdn.com/bf.svg", callingCodes: "226" },
    { name: "Burundi", flags: "https://flagcdn.com/bi.svg", callingCodes: "257" },
    { name: "Cambodia", flags: "https://flagcdn.com/kh.svg", callingCodes: "855" },
    { name: "Cameroon", flags: "https://flagcdn.com/cm.svg", callingCodes: "237" },
    { name: "Canada", flags: "https://flagcdn.com/ca.svg", callingCodes: "1" },
    { name: "Cape Verde", flags: "https://flagcdn.com/cv.svg", callingCodes: "238" },
    { name: "Central African Republic", flags: "https://flagcdn.com/cf.svg", callingCodes: "236" },
    { name: "Chad", flags: "https://flagcdn.com/td.svg", callingCodes: "235" },
    { name: "Chile", flags: "https://flagcdn.com/cl.svg", callingCodes: "56" },
    { name: "China", flags: "https://flagcdn.com/cn.svg", callingCodes: "86" },
    { name: "Colombia", flags: "https://flagcdn.com/co.svg", callingCodes: "57" },
    { name: "Comoros", flags: "https://flagcdn.com/km.svg", callingCodes: "269" },
    { name: "Congo", flags: "https://flagcdn.com/cg.svg", callingCodes: "242" },
    { name: "Costa Rica", flags: "https://flagcdn.com/cr.svg", callingCodes: "506" },
    { name: "Croatia", flags: "https://flagcdn.com/hr.svg", callingCodes: "385" },
    { name: "Cuba", flags: "https://flagcdn.com/cu.svg", callingCodes: "53" },
    { name: "Cyprus", flags: "https://flagcdn.com/cy.svg", callingCodes: "357" },
    { name: "Czech Republic", flags: "https://flagcdn.com/cz.svg", callingCodes: "420" },
    { name: "Denmark", flags: "https://flagcdn.com/dk.svg", callingCodes: "45" },
    { name: "Djibouti", flags: "https://flagcdn.com/dj.svg", callingCodes: "253" },
    { name: "Dominica", flags: "https://flagcdn.com/dm.svg", callingCodes: "1767" },
    { name: "Dominican Republic", flags: "https://flagcdn.com/do.svg", callingCodes: "1809" },
    { name: "East Timor", flags: "https://flagcdn.com/tl.svg", callingCodes: "670" },
    { name: "Ecuador", flags: "https://flagcdn.com/ec.svg", callingCodes: "593" },
    { name: "Egypt", flags: "https://flagcdn.com/eg.svg", callingCodes: "20" },
    { name: "El Salvador", flags: "https://flagcdn.com/sv.svg", callingCodes: "503" },
    { name: "Equatorial Guinea", flags: "https://flagcdn.com/gq.svg", callingCodes: "240" },
    { name: "Eritrea", flags: "https://flagcdn.com/er.svg", callingCodes: "291" },
    { name: "Estonia", flags: "https://flagcdn.com/ee.svg", callingCodes: "372" },
    { name: "Ethiopia", flags: "https://flagcdn.com/et.svg", callingCodes: "251" },
    { name: "Fiji", flags: "https://flagcdn.com/fj.svg", callingCodes: "679" },
    { name: "Finland", flags: "https://flagcdn.com/fi.svg", callingCodes: "358" },
    { name: "France", flags: "https://flagcdn.com/fr.svg", callingCodes: "33" },
    { name: "Gabon", flags: "https://flagcdn.com/ga.svg", callingCodes: "241" },
    { name: "Gambia", flags: "https://flagcdn.com/gm.svg", callingCodes: "220" },
    { name: "Georgia", flags: "https://flagcdn.com/ge.svg", callingCodes: "995" },
    { name: "Germany", flags: "https://flagcdn.com/de.svg", callingCodes: "49" },
    { name: "Ghana", flags: "https://flagcdn.com/gh.svg", callingCodes: "233" },
    { name: "Greece", flags: "https://flagcdn.com/gr.svg", callingCodes: "30" },
    { name: "Grenada", flags: "https://flagcdn.com/gd.svg", callingCodes: "1473" },
    { name: "Guatemala", flags: "https://flagcdn.com/gt.svg", callingCodes: "502" },
    { name: "Guinea", flags: "https://flagcdn.com/gn.svg", callingCodes: "224" },
    { name: "Guinea-Bissau", flags: "https://flagcdn.com/gw.svg", callingCodes: "245" },
    { name: "Guyana", flags: "https://flagcdn.com/gy.svg", callingCodes: "592" },
    { name: "Haiti", flags: "https://flagcdn.com/ht.svg", callingCodes: "509" },
    { name: "Honduras", flags: "https://flagcdn.com/hn.svg", callingCodes: "504" },
    { name: "Hungary", flags: "https://flagcdn.com/hu.svg", callingCodes: "36" },
    { name: "Iceland", flags: "https://flagcdn.com/is.svg", callingCodes: "354" },
    { name: "India", flags: "https://flagcdn.com/in.svg", callingCodes: "91" },
    { name: "Indonesia", flags: "https://flagcdn.com/id.svg", callingCodes: "62" },
    { name: "Iran", flags: "https://flagcdn.com/ir.svg", callingCodes: "98" },
    { name: "Iraq", flags: "https://flagcdn.com/iq.svg", callingCodes: "964" },
    { name: "Ireland", flags: "https://flagcdn.com/ie.svg", callingCodes: "353" },
    { name: "Israel", flags: "https://flagcdn.com/il.svg", callingCodes: "972" },
    { name: "Italy", flags: "https://flagcdn.com/it.svg", callingCodes: "39" },
    { name: "Jamaica", flags: "https://flagcdn.com/jm.svg", callingCodes: "1876" },
    { name: "Japan", flags: "https://flagcdn.com/jp.svg", callingCodes: "81" },
    { name: "Jordan", flags: "https://flagcdn.com/jo.svg", callingCodes: "962" },
    { name: "Kazakhstan", flags: "https://flagcdn.com/kz.svg", callingCodes: "7" },
    { name: "Kenya", flags: "https://flagcdn.com/ke.svg", callingCodes: "254" },
    { name: "Kiribati", flags: "https://flagcdn.com/ki.svg", callingCodes: "686" },
    { name: "North Korea", flags: "https://flagcdn.com/kp.svg", callingCodes: "850" },
    { name: "South Korea", flags: "https://flagcdn.com/kr.svg", callingCodes: "82" },
    { name: "Kuwait", flags: "https://flagcdn.com/kw.svg", callingCodes: "965" },
    { name: "Kyrgyzstan", flags: "https://flagcdn.com/kg.svg", callingCodes: "996" },
    { name: "Laos", flags: "https://flagcdn.com/la.svg", callingCodes: "856" },
    { name: "Latvia", flags: "https://flagcdn.com/lv.svg", callingCodes: "371" },
    { name: "Lebanon", flags: "https://flagcdn.com/lb.svg", callingCodes: "961" },
    { name: "Lesotho", flags: "https://flagcdn.com/ls.svg", callingCodes: "266" },
    { name: "Liberia", flags: "https://flagcdn.com/lr.svg", callingCodes: "231" },
    { name: "Libya", flags: "https://flagcdn.com/ly.svg", callingCodes: "218" },
    { name: "Liechtenstein", flags: "https://flagcdn.com/li.svg", callingCodes: "423" },
    { name: "Lithuania", flags: "https://flagcdn.com/lt.svg", callingCodes: "370" },
    { name: "Luxembourg", flags: "https://flagcdn.com/lu.svg", callingCodes: "352" },
    { name: "Macedonia", flags: "https://flagcdn.com/mk.svg", callingCodes: "389" },
    { name: "Madagascar", flags: "https://flagcdn.com/mg.svg", callingCodes: "261" },
    { name: "Malawi", flags: "https://flagcdn.com/mw.svg", callingCodes: "265" },
    { name: "Malaysia", flags: "https://flagcdn.com/my.svg", callingCodes: "60" },
    { name: "Maldives", flags: "https://flagcdn.com/mv.svg", callingCodes: "960" },
    { name: "Mali", flags: "https://flagcdn.com/ml.svg", callingCodes: "223" },
    { name: "Malta", flags: "https://flagcdn.com/mt.svg", callingCodes: "356" },
    { name: "Marshall Islands", flags: "https://flagcdn.com/mh.svg", callingCodes: "692" },
    { name: "Mauritania", flags: "https://flagcdn.com/mr.svg", callingCodes: "222" },
    { name: "Mauritius", flags: "https://flagcdn.com/mu.svg", callingCodes: "230" },
    { name: "Mexico", flags: "https://flagcdn.com/mx.svg", callingCodes: "52" },
    { name: "Micronesia", flags: "https://flagcdn.com/fm.svg", callingCodes: "691" },
    { name: "Moldova", flags: "https://flagcdn.com/md.svg", callingCodes: "373" },
    { name: "Monaco", flags: "https://flagcdn.com/mc.svg", callingCodes: "377" },
    { name: "Mongolia", flags: "https://flagcdn.com/mn.svg", callingCodes: "976" },
    { name: "Montenegro", flags: "https://flagcdn.com/me.svg", callingCodes: "382" },
    { name: "Morocco", flags: "https://flagcdn.com/ma.svg", callingCodes: "212" },
    { name: "Mozambique", flags: "https://flagcdn.com/mz.svg", callingCodes: "258" },
    { name: "Myanmar", flags: "https://flagcdn.com/mm.svg", callingCodes: "95" },
    { name: "Namibia", flags: "https://flagcdn.com/na.svg", callingCodes: "264" },
    { name: "Nauru", flags: "https://flagcdn.com/nr.svg", callingCodes: "674" },
    { name: "Nepal", flags: "https://flagcdn.com/np.svg", callingCodes: "977" },
    { name: "Netherlands", flags: "https://flagcdn.com/nl.svg", callingCodes: "31" },
    { name: "New Zealand", flags: "https://flagcdn.com/nz.svg", callingCodes: "64" },
    { name: "Nicaragua", flags: "https://flagcdn.com/ni.svg", callingCodes: "505" },
    { name: "Niger", flags: "https://flagcdn.com/ne.svg", callingCodes: "227" },
    { name: "Nigeria", flags: "https://flagcdn.com/ng.svg", callingCodes: "234" },
    { name: "Norway", flags: "https://flagcdn.com/no.svg", callingCodes: "47" },
    { name: "Oman", flags: "https://flagcdn.com/om.svg", callingCodes: "968" },
    { name: "Pakistan", flags: "https://flagcdn.com/pk.svg", callingCodes: "92" },
    { name: "Palau", flags: "https://flagcdn.com/pw.svg", callingCodes: "680" },
    { name: "Panama", flags: "https://flagcdn.com/pa.svg", callingCodes: "507" },
    { name: "Papua New Guinea", flags: "https://flagcdn.com/pg.svg", callingCodes: "675" },
    { name: "Paraguay", flags: "https://flagcdn.com/py.svg", callingCodes: "595" },
    { name: "Peru", flags: "https://flagcdn.com/pe.svg", callingCodes: "51" },
    { name: "Philippines", flags: "https://flagcdn.com/ph.svg", callingCodes: "63" },
    { name: "Poland", flags: "https://flagcdn.com/pl.svg", callingCodes: "48" },
    { name: "Portugal", flags: "https://flagcdn.com/pt.svg", callingCodes: "351" },
    { name: "Qatar", flags: "https://flagcdn.com/qa.svg", callingCodes: "974" },
    { name: "Romania", flags: "https://flagcdn.com/ro.svg", callingCodes: "40" },
    { name: "Russia", flags: "https://flagcdn.com/ru.svg", callingCodes: "7" },
    { name: "Rwanda", flags: "https://flagcdn.com/rw.svg", callingCodes: "250" },
    { name: "Saint Kitts and Nevis", flags: "https://flagcdn.com/kn.svg", callingCodes: "1869" },
    { name: "Saint Lucia", flags: "https://flagcdn.com/lc.svg", callingCodes: "1758" },
    { name: "Saint Vincent and the Grenadines", flags: "https://flagcdn.com/vc.svg", callingCodes: "1784" },
    { name: "Samoa", flags: "https://flagcdn.com/ws.svg", callingCodes: "685" },
    { name: "San Marino", flags: "https://flagcdn.com/sm.svg", callingCodes: "378" },
    { name: "Sao Tome and Principe", flags: "https://flagcdn.com/st.svg", callingCodes: "239" },
    { name: "Saudi Arabia", flags: "https://flagcdn.com/sa.svg", callingCodes: "966" },
    { name: "Senegal", flags: "https://flagcdn.com/sn.svg", callingCodes: "221" },
    { name: "Serbia", flags: "https://flagcdn.com/rs.svg", callingCodes: "381" },
    { name: "Seychelles", flags: "https://flagcdn.com/sc.svg", callingCodes: "248" },
    { name: "Sierra Leone", flags: "https://flagcdn.com/sl.svg", callingCodes: "232" },
    { name: "Singapore", flags: "https://flagcdn.com/sg.svg", callingCodes: "65" },
    { name: "Slovakia", flags: "https://flagcdn.com/sk.svg", callingCodes: "421" },
    { name: "Slovenia", flags: "https://flagcdn.com/si.svg", callingCodes: "386" },
    { name: "Solomon Islands", flags: "https://flagcdn.com/sb.svg", callingCodes: "677" },
    { name: "Somalia", flags: "https://flagcdn.com/so.svg", callingCodes: "252" },
    { name: "South Africa", flags: "https://flagcdn.com/za.svg", callingCodes: "27" },
    { name: "South Sudan", flags: "https://flagcdn.com/ss.svg", callingCodes: "211" },
    { name: "Spain", flags: "https://flagcdn.com/es.svg", callingCodes: "34" },
    { name: "Sri Lanka", flags: "https://flagcdn.com/lk.svg", callingCodes: "94" },
    { name: "Sudan", flags: "https://flagcdn.com/sd.svg", callingCodes: "249" },
    { name: "Suriname", flags: "https://flagcdn.com/sr.svg", callingCodes: "597" },
    { name: "Swaziland", flags: "https://flagcdn.com/sz.svg", callingCodes: "268" },
    { name: "Sweden", flags: "https://flagcdn.com/se.svg", callingCodes: "46" },
    { name: "Switzerland", flags: "https://flagcdn.com/ch.svg", callingCodes: "41" },
    { name: "Syria", flags: "https://flagcdn.com/sy.svg", callingCodes: "963" },
    { name: "Taiwan", flags: "https://flagcdn.com/tw.svg", callingCodes: "886" },
    { name: "Tajikistan", flags: "https://flagcdn.com/tj.svg", callingCodes: "992" },
    { name: "Tanzania", flags: "https://flagcdn.com/tz.svg", callingCodes: "255" },
    { name: "Thailand", flags: "https://flagcdn.com/th.svg", callingCodes: "66" },
    { name: "Togo", flags: "https://flagcdn.com/tg.svg", callingCodes: "228" },
    { name: "Tonga", flags: "https://flagcdn.com/to.svg", callingCodes: "676" },
    { name: "Trinidad and Tobago", flags: "https://flagcdn.com/tt.svg", callingCodes: "1868" },
    { name: "Tunisia", flags: "https://flagcdn.com/tn.svg", callingCodes: "216" },
    { name: "Turkey", flags: "https://flagcdn.com/tr.svg", callingCodes: "90" },
    { name: "Turkmenistan", flags: "https://flagcdn.com/tm.svg", callingCodes: "993" },
    { name: "Tuvalu", flags: "https://flagcdn.com/tv.svg", callingCodes: "688" },
    { name: "Uganda", flags: "https://flagcdn.com/ug.svg", callingCodes: "256" },
    { name: "Ukraine", flags: "https://flagcdn.com/ua.svg", callingCodes: "380" },
    { name: "United Arab Emirates", flags: "https://flagcdn.com/ae.svg", callingCodes: "971" },
    { name: "United Kingdom", flags: "https://flagcdn.com/gb.svg", callingCodes: "44" },
    { name: "United States", flags: "https://flagcdn.com/us.svg", callingCodes: "1" },
    { name: "Uruguay", flags: "https://flagcdn.com/uy.svg", callingCodes: "598" },
    { name: "Uzbekistan", flags: "https://flagcdn.com/uz.svg", callingCodes: "998" },
    { name: "Vanuatu", flags: "https://flagcdn.com/vu.svg", callingCodes: "678" },
    { name: "Vatican City", flags: "https://flagcdn.com/va.svg", callingCodes: "379" },
    { name: "Venezuela", flags: "https://flagcdn.com/ve.svg", callingCodes: "58" },
    { name: "Vietnam", flags: "https://flagcdn.com/vn.svg", callingCodes: "84" },
    { name: "Yemen", flags: "https://flagcdn.com/ye.svg", callingCodes: "967" },
    { name: "Zambia", flags: "https://flagcdn.com/zm.svg", callingCodes: "260" },
    { name: "Zimbabwe", flags: "https://flagcdn.com/zw.svg", callingCodes: "263" }
  ]