export const adjectives = [
  { key: "happy", label: "Happy" },
  { key: "sad", label: "Sad" },
  { key: "bright", label: "Bright" },
  { key: "dark", label: "Dark" },
  { key: "strong", label: "Strong" },
  { key: "weak", label: "Weak" },
  { key: "fast", label: "Fast" },
  { key: "slow", label: "Slow" },
  { key: "big", label: "Big" },
  { key: "small", label: "Small" },
  { key: "friendly", label: "Friendly" },
  { key: "angry", label: "Angry" },
  { key: "quiet", label: "Quiet" },
  { key: "loud", label: "Loud" },
  { key: "sharp", label: "Sharp" },
  { key: "soft", label: "Soft" },
  { key: "clean", label: "Clean" },
  { key: "dirty", label: "Dirty" },
  { key: "brave", label: "Brave" },
  { key: "calm", label: "Calm" },
]

export const animals = [
  { key: "lion", label: "Lion" },
  { key: "tiger", label: "Tiger" },
  { key: "elephant", label: "Elephant" },
  { key: "giraffe", label: "Giraffe" },
  { key: "zebra", label: "Zebra" },
  { key: "kangaroo", label: "Kangaroo" },
  { key: "penguin", label: "Penguin" },
  { key: "dolphin", label: "Dolphin" },
  { key: "shark", label: "Shark" },
  { key: "eagle", label: "Eagle" },
  { key: "owl", label: "Owl" },
  { key: "rabbit", label: "Rabbit" },
  { key: "bear", label: "Bear" },
  { key: "wolf", label: "Wolf" },
  { key: "fox", label: "Fox" },
  { key: "snake", label: "Snake" },
  { key: "turtle", label: "Turtle" },
  { key: "frog", label: "Frog" },
  { key: "horse", label: "Horse" },
  { key: "monkey", label: "Monkey" },
]
