export const listSellersAvatar = [
  { name: "Eagle", src: "/account/avatars/avatar_aguila.png" },
  { name: "Owl", src: "/account/avatars/avatar_buho.png" },
  { name: "Donkey", src: "/account/avatars/avatar_burro.png" },
  { name: "Horse", src: "/account/avatars/avatar_caballo.png" },
  { name: "Kangaroo", src: "/account/avatars/avatar_canguro.png" },
  { name: "Rabbit", src: "/account/avatars/avatar_conejo.png" },
  { name: "Dolphin", src: "/account/avatars/avatar_delfin.png" },
  { name: "Elephant", src: "/account/avatars/avatar_elefante.png" },
  { name: "Giraffe", src: "/account/avatars/avatar_jirafa.png" },
  { name: "Wolf", src: "/account/avatars/avatar_lobo.png" },
  { name: "Bear", src: "/account/avatars/avatar_oso.png" },
  { name: "Penguin", src: "/account/avatars/avatar_pinguino.png" },
  { name: "Frog", src: "/account/avatars/avatar_rana.png" },
  { name: "Mouse", src: "/account/avatars/avatar_raton.png" },
  { name: "Snake", src: "/account/avatars/avatar_serpiente.png" },
  { name: "Shark", src: "/account/avatars/avatar_tiburon.png" },
  { name: "Tiger", src: "/account/avatars/avatar_tigre.png" },
  { name: "Turtle", src: "/account/avatars/avatar_tortuga.png" },
  { name: "Zebra", src: "/account/avatars/avatar_zebra.png" },
  { name: "Fox", src: "/account/avatars/avatar_zorro.png" },
]
